scenerygraphics/sciview

src/main/java/sc/fiji/threed/SceneNodePropertiesEditor.java
This is the properties dialog, we were discussing. Feel free to refactor it :-)
=> Add first version of a properties dialog

src/main/java/sc/fiji/threed/AddLabelImage.java, src/main/java/sc/fiji/threed/SceneNodePropertiesEditor.java
Adding a class which allows to read images as label maps and show the objects in 3D. Feel free  to refactor it :-)
=> Adding an importer for label maps

pom.xml, src/main/java/sc/fiji/threed/ThreeDViewer.java
This makes the necessary code changes to account for backwards incompatibilities in the API. It also adds a couple of missing `@Override` annotations, and organizes some import statements.
=> Update to release version 0.1.0 of scenery

pom.xml, src/main/java/sc/iview/SciView.java
Also Readding imagej-legacy to get the file dialog working
=> Rendering for point clouds and import of xyz point clouds

src/main/java/sc/iview/commands/MenuWeights.java, src/main/java/sc/iview/commands/demo/GameOfLife3D.java
=> Add Conway's Game of Life 3D

.idea/.name, .idea/compiler.xml, .idea/encodings.xml, .idea/misc.xml, .idea/vcs.xml, .idea/workspace.xml, src/main/java/sc/iview/SciView.java, src/main/java/sc/iview/commands/demo/GameOfLife3D.java
Now able to adjust fps scroll speed
=> ScrollSpeed

pom.xml, src/main/java/sc/iview/SciView.java
This PR includes fixes -- also from the scenery side -- that improve the interop between JavaFX and Swing, particularly:
* dialog hangs (#138)
* a race condition leading to invisible volumes (#139)
=> Improved Swing/JavaFX interop

src/main/java/sc/iview/SciView.java
=> Make SciView.addVolume accept RAI instead of II

src/main/java/sc/iview/SciView.java, src/main/java/sc/iview/commands/MenuWeights.java, src/main/java/sc/iview/commands/edit/NodePropertyEditor.java, src/main/java/sc/iview/commands/view/NodePropertyEditor.java, src/main/java/sc/iview/commands/view/ToggleInspector.java
To make it easier for users to understand and modify a scene, this adds the Nodes Properties window as panels in a combined single collapsible window with scenery. Addresses #159
=> Node Properties inspector in a single collapsible window with scenery

src/main/java/sc/iview/SciView.java, src/main/java/sc/iview/commands/MenuWeights.java, src/main/java/sc/iview/commands/edit/NodeProperties.java, src/main/java/sc/iview/commands/edit/NodePropertyEditor.java
Reverts scenerygraphics/sciview#165
=> Revert "Node Properties inspector in a single collapsible window with scenery"

src/main/java/sc/iview/commands/edit/ToggleFloor.java
Reverts scenerygraphics/sciview#166
=> Revert "Publish to event service on floor toggle"

src/main/java/sc/iview/SciView.java, src/main/java/sc/iview/commands/MenuWeights.java, src/main/java/sc/iview/commands/view/NodePropertyEditor.java, src/main/java/sc/iview/commands/view/ToggleInspector.java
Reverts scenerygraphics/sciview#168. It's kind of hilarious 😆
=> Revert "Revert "Node Properties inspector in a single collapsible window with scenery""

src/main/java/sc/iview/SciView.java, src/main/java/sc/iview/ui/REPLEditor.java, src/main/java/sc/iview/ui/REPLPane.java, src/main/resources/sc/iview/startup.py
This PR adds a custom REPL pane, adds syntax highlighting and automagically imports ClearGL and scenery primitives in the startup script.
=> Beautify the REPL

src/main/java/sc/iview/Controls.kt
Measures the distance between two meshes. Again, it has an arbitrary key binding ("M").
Further development on #37
=> Added DistanceMeasurement to the controls.

build.gradle.kts, src/main/java/sc/iview/commands/demo/basic/ImagePlaneDemo.java, src/main/kotlin/sc/iview/Controls.kt, src/main/kotlin/sc/iview/commands/view/SetLUT.kt, src/main/kotlin/sc/iview/ui/SwingMainWindow.kt
This PR updates sciview to use the latest scenery version, including some API changes.
It also bumps Kotlin to 1.5.10, and does some minor cleanup.
=> Update to Kotlin 1.5.10, update to latest scenery version

src/main/kotlin/sc/iview/commands/edit/add/AddProtein.kt, src/main/kotlin/sc/iview/commands/edit/add/AddProteinFromFiles.kt
This PR adds a new command to add proteins from supported file types (such as PDB, MMTF, CIF).
=> Add proteins from files

CITATION.cff
Adds citation information in the new format, closes #391.
=> Add CITATION.cff file for citation information

src/main/kotlin/sc/iview/SciView.kt, src/main/kotlin/sc/iview/Utils.kt, src/main/kotlin/sc/iview/commands/view/Screenshot.kt
This PR avoids unnecessary disk writes. when taking screenshots.
=> SciView/Utils/Screenshot: Improve screenshot functionality

build.gradle.kts
=> Kotlin versions

src/main/kotlin/sc/iview/commands/MenuWeights.kt, src/main/kotlin/sc/iview/commands/edit/Properties.kt, src/main/kotlin/sc/iview/commands/edit/VolumeSelectorWidget.kt, src/main/kotlin/sc/iview/commands/edit/add/AddSlicingPlane.kt
=> Add slicing ui

src/main/kotlin/sc/iview/commands/demo/advanced/LoadCremiDatasetAndNeurons.kt
Code was modified so that running the demo in Sciview will automatically download Dataset A from the cremi website (https://cremi.org/data/) instead of the user having to manually download and select a file. This was done to make running the demo simpler and more convenient.
=> Automatic file download for Sciview demo

src/main/kotlin/sc/iview/commands/demo/advanced/LoadCremiDatasetAndNeurons.kt
This closes https://github.com/scenerygraphics/sciview/issues/455
=> Make neuron meshes children of volume

src/main/kotlin/sc/iview/Controls.kt, src/main/kotlin/sc/iview/controls/behaviours/ClickAndDragWrapper.kt
=> Wrap fpsControl to allow node selection on clicks without drag

src/main/java/sc/iview/commands/demo/animation/SceneRiggingDemo.java
Closes https://github.com/scenerygraphics/sciview/issues/450
=> Fix STL opening error in SceneRiggingDemo

src/main/kotlin/sc/iview/commands/view/StartRecordingVideo.kt
This PR is intended to close https://github.com/scenerygraphics/sciview/issues/199, and it looks like part of that work was actually already done and merged. 
However, I did open https://github.com/scenerygraphics/sciview/issues/460. It would be cool if that could be added to this PR, although that isnt necessary for 1.0.0.
=> Add parameter to control HW encoding

src/main/java/sc/iview/commands/edit/add/AddSphere.java, src/main/kotlin/sc/iview/commands/edit/add/AddBox.kt, src/main/kotlin/sc/iview/commands/edit/add/AddLine.kt
Closes https://github.com/scenerygraphics/sciview/issues/470
=> Specify that color Parameters are not required

src/main/kotlin/sc/iview/SplashLabel.kt
Closes https://github.com/scenerygraphics/sciview/issues/403
=> Use unicode value for the heart on the splash screen

src/main/kotlin/sc/iview/commands/MenuWeights.kt, src/main/kotlin/sc/iview/commands/edit/ResetScene.kt
Closes https://github.com/scenerygraphics/sciview/issues/407
=> Add a command to reset the scene to initial conditions

src/main/kotlin/sc/iview/commands/view/StartRecordingVideo.kt
Closes https://github.com/scenerygraphics/sciview/issues/460
Closes https://github.com/scenerygraphics/sciview/issues/331
=> Add support for choosing filename for saving videos

src/main/kotlin/sc/iview/commands/edit/add/AddVolume.kt
Closes https://github.com/scenerygraphics/sciview/issues/390
Closes https://github.com/scenerygraphics/sciview/issues/420
=> Call setVoxelDimension at the right time

src/main/kotlin/sc/iview/commands/demo/advanced/LoadCremiDatasetAndNeurons.kt
Closes https://github.com/scenerygraphics/sciview/issues/453
=> Catch HDF5 reading exception in CREMI

src/main/kotlin/sc/iview/ui/SwingMainWindow.kt
Closes https://github.com/scenerygraphics/sciview/issues/440
=> Adjust scroll speed for properties and tree views to be normal

src/main/java/sc/iview/commands/edit/add/AddOrientationCompass.java
Closes https://github.com/scenerygraphics/sciview/issues/485
=> Fix compass exception and location in scene graph

src/main/kotlin/sc/iview/commands/edit/Properties.kt
Closes https://github.com/scenerygraphics/sciview/issues/441
=> Remove RenderingMethod options for Volume

src/main/kotlin/sc/iview/SciView.kt, src/main/kotlin/sc/iview/commands/edit/ResetScene.kt
Closes https://github.com/scenerygraphics/sciview/issues/534
=> Fix ResetScene to update scene tree

src/main/kotlin/sc/iview/commands/MenuWeights.kt, src/main/kotlin/sc/iview/commands/demo/advanced/LoadFlybrainOutOfCore.kt, src/main/kotlin/sc/iview/commands/edit/Properties.kt
This ports @skalarproduktraum and @tpietzsch's flybrain demo from scenery to sciview
=> First pass at Flybrain Demo

build.gradle.kts, settings.gradle.kts
=> Bump version to 0.2.0

gradle/wrapper/gradle-wrapper.properties, gradlew.bat
=> Build: Bump Gradle to 8.7

build.gradle.kts, gradle.properties, settings.gradle.kts
This PR saves the project version in the `META-INF/MANIFEST.MF` file for easier discovery. It also moves the project version definition to `gradle.properties`.
=> Save version in manifest

src/main/kotlin/sc/iview/SciView.kt
Closes https://github.com/scenerygraphics/sciview/issues/572
=> Fix for duplicate generation of unique names
