pom.xml
src/main/java/sc/iview/SciView.java

This updates scenery to 0.2.0-SNAPSHOT and fixes some issues, e.g. a hardcoded colormap path.

Fixes to include scenery 0.2.0-SNAPSHOT

---

src/main/java/sc/iview/SciView.java
src/main/java/sc/iview/commands/demo/VolumeRenderDemo.java

This works for images that are uniform over all dimensions. There is an upstream bug that leads to an off-by-one error in 3D texture allocation (see JOGL GLBuffers image size allocations). The plan is to account for this in ClearGL.

General volume mesh overlay fix

---

src/main/java/sc/iview/DefaultSciViewService.java
src/main/java/sc/iview/commands/view/SaveCameraConfiguration.java

This allows to use `#@ SciView sciview` in scripts, instead of using the fully qualified class name.

Add script parameter alias for SciView

---

src/main/java/sc/iview/SciView.java

Removes the `SciView.useJavaFX` field (which is always true).
If there should be another path besides javaFX in the future, we can bring it back...

Remove unused "useJavaFX" switch for now

---

src/main/java/sc/iview/commands/edit/ToggleFloor.java

Clicking the Floor Toggle command on the menu was not publishing to the event service. This has been corrected. Addresses #163

Publish to event service on floor toggle

---

pom.xml

For artifacts managed by `pom-scijava`, we don't need to specify a `<version>` tag. It's sufficient to set to set a version `<property>` to override the version if necessary.
Also remove duplicate (optional) dependency `imagej-ui-swing`, as it is listed as dependency already.

Remove redundant version tags in pom.xml

---

src/main/java/sc/iview/commands/edit/Properties.kt

* hides the timepoint slider, the play-pause button and the speed button in case a volume has not more than one timepoint

Properties: Hide timepoint UI elements for volumes without timepoints

---

src/main/java/sc/iview/ui/SwingMainWindow.kt

Tested to work with azul-1.8.0_275 on Ubuntu w/ Nvidia

Remove the forced use of OpenGLRenderer on java8

---

pom.xml

This is breaking L&F changes in SNT that [declares](https://github.com/morphonets/SNT/blob/2bd09b8e5d1b5a44b44d9379a430c801d8e51b5f/pom.xml#L166-L168) the latest FlatLaf version.
Somehow, when subscribed to both SNT and sciview update sites, the updater retains the outdated artifact, so this is the quickest way to fix it. 
Either way, _many_ improvements are in place with version 1.1, so it makes sense to update.
More details here: https://github.com/JFormDesigner/FlatLaf/issues/280

Update FlatLaf dependency

---

src/main/java/sc/iview/ui/SwingGroupingInputHarvester.kt
src/main/java/sc/iview/ui/SwingNodePropertyEditor.kt

- Open and close input harvester groups via single click (this is the expected behaviour for a group label with an arrow)
- Remove empty space on the right of the `SwingNodePropertyEditor`:
- update tree on node change

PropertyEditor enhancements

---

src/main/java/sc/iview/SciView.kt
src/main/java/sc/iview/commands/demo/advanced/LoadCremiDatasetAndNeurons.kt
src/main/java/sc/iview/commands/demo/animation/GameOfLife3D.kt
src/main/java/sc/iview/commands/demo/animation/VolumeTimeseriesDemo.kt
src/main/java/sc/iview/commands/demo/basic/VolumeRenderDemo.kt
src/main/java/sc/iview/commands/edit/add/AddVolume.kt

- Makes `add` methods return the type of the added node if possible, e.g. `addVolume(): Volume` instead of `addVolume(): Node?`
- Adds a lambda block parameter to `add` methods to allow something like this:
```
sciView.addVolume(dataset, floatArrayOf(1f, 1f, 1f, 1f)) {
pixelToWorldRatio = 10f
name = "Volume Render Demo"
dirty = true
}
```
.. instead of 
```
val v = sciView.addVolume(dataset, floatArrayOf(1f, 1f, 1f, 1f))
v.pixelToWorldRatio = 10f
v.name = "Volume Render Demo"
v.dirty = true
```

SciView: improve add methods

---

build.gradle.kts
gradle.properties
settings.gradle.kts

This PR fixes the BigVolumeViewer version in the Gradle build to the correct jitpack one, and removes the reference to release version 0.1.8. This can be changed back after tpietzsch/jogl-minimal#14 is merged. See also scenerygraphics/scenery#402.
Together with the scenery PR, this PR solves the issue of the volume demos silently failing.

Fix BigVolumeViewer version in Gradle build

---

build.gradle.kts
buildSrc/src/main/kotlin/sciview/utils.kt
gradle/wrapper/gradle-wrapper.properties
settings.gradle.kts
src/main/kotlin/sc/iview/SplashLabel.kt

- Gradle 7.0
- Gradle Catalog centralized versions, safe-type dependency accessors
- relying on a more vanilla Gradle api (`::implementation` instead `::sciJava`)
- sciJava plugin alignment (against 30.0.0, with a small [deviation](https://github.com/scenerygraphics/sciview/commit/622d0dba6ab829f7d5b1da0539294bc909ebbfb7#r50038119)), workaround for jitpack issue

Gradle catalog

---

src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt

This issue fixes the NPE that occurs when right-clicking on a Scene node in the inspector. Fixes #377.

SwingNodePropertyEditor: Fix NPE when right-clicking on a Scene

---

src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/demo/animation/GameOfLife3D.kt
src/main/kotlin/sc/iview/commands/edit/Properties.kt
src/main/kotlin/sc/iview/ui/CustomPropertyUI.kt
src/main/kotlin/sc/iview/ui/SwingGroupingInputHarvester.kt
src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt

This PR adds the CustomPropertyUI class in order to enable Commands to add their own UI items to the property inspector. 
Custom UI based on a Command's inputs can be added e.g. as (taken from `GameOfLife3D`)
```kotlin
node.metadata["sciview-inspector"] = CustomPropertyUI(
this,
listOf(
"starvation",
"suffocation",
"birth",
"connectedness",
"playSpeed",
"play",
"pause"
)
)
```
The result then is the following:

Add CustomPropertyUI

---

.jitpack.yml
build.gradle.kts
scripts/process_pom.sh

Manually adding `<type>pom</type>` to lwjgl-pom and kotlin-pom fixes dependency resolution issues, but then there is a runtime jackson issue

Jitpack pom

---

build.gradle.kts

This PR:
* bumps Kotlin to 1.6.10
* updates all jackson dependencies to the latest version
* removes explicit lwjgl dependency
* removes spirvcrossj

Gradle: Bump to Kotlin 1.6.10, update dependencies, remove spirvcrossj

---

.jitpack.yml
build.gradle.kts

This PR switches the build process on jitpack to Java 11, using Eclipse Temurin.

jitpack build: Switch to Java 11

---

src/main/kotlin/sc/iview/commands/demo/advanced/LoadCremiDatasetAndNeurons.kt

Downloading and reading take enough time that it is worth a status update.

Add status messages for downloading and reading

---

src/main/java/sc/iview/commands/help/Help.java
src/main/kotlin/sc/iview/Controls.kt
src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/edit/settings/KeyBindings.kt
src/main/kotlin/sc/iview/controls/behaviours/CameraTranslateControl.kt
src/main/kotlin/sc/iview/process/ControlPoints.kt
src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt

also inputhandler getter methods get cleaned up.
Closes https://github.com/scenerygraphics/sciview/issues/409

Clear property editor on delete

---

src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/view/ToggleBoundingGrid.kt

ToggleBoundingGrid now works for all nodes not just meshed. 
closes #448

Bounding grids for all

---

src/main/kotlin/sc/iview/commands/edit/Properties.kt

Closes https://github.com/scenerygraphics/sciview/issues/175
Closes https://github.com/scenerygraphics/sciview/issues/439

Improvements to the properties panel to close multiple issues

---

src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt

Improved the help text container when no node is selected to have a but of padding.

SwingNodePropertyEditor.kt: Help text nice formatted

---

src/main/java/sc/iview/commands/edit/add/AddCamera.java
src/main/java/sc/iview/commands/edit/add/AddLabelImage.java
src/main/java/sc/iview/commands/edit/add/AddOrientationCompass.java
src/main/java/sc/iview/commands/edit/add/AddSphere.java
src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/edit/add/AddBox.kt
src/main/kotlin/sc/iview/commands/edit/add/AddLine.kt
src/main/kotlin/sc/iview/commands/edit/add/AddVolume.kt

Closes https://github.com/scenerygraphics/sciview/issues/471

Use unique names and retain names from filenames

---

src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/edit/Properties.kt
src/main/kotlin/sc/iview/commands/view/SetLUT.kt
src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt

Closes https://github.com/scenerygraphics/sciview/issues/129
Closes https://github.com/scenerygraphics/sciview/issues/441

Fix LUT display and persistence for SetLUT and Properties panel

---

build.gradle.kts
src/main/kotlin/sc/iview/Controls.kt
src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/demo/advanced/LoadCremiDatasetAndNeurons.kt
src/main/kotlin/sc/iview/commands/edit/settings/KeyBindings.kt

Closes https://github.com/scenerygraphics/sciview/issues/452

Use XDG-compliant paths for cache and config files

---

src/main/kotlin/sc/iview/commands/edit/Properties.kt

Fixes a bug where every node had an edgeWidth attribute in the Properties panel.

Remove edgeWidth for Nodes that aren't Line

---

src/main/kotlin/sc/iview/SciView.kt

this is a followup of the issue #497, it is
- deprecating `addChild()`
- cosmetics: injecting `@Deprecate` tag to `removeChild()` 
- adding a shortcut variant of `addNode()`
demo example
```java
SciView sv = SciView.create();
Sphere j = new Sphere();
j.setName("addnode");
sv.addNode(j, false);
//NB: renders already but lists not yet in the scene inspector panel
Sphere s = new Sphere();
s.setName("addchild");
sv.addNode(s, j);
//NB: only now all "pending" added nodes will get listed in the inspector panel
```

Convenience node adders, based on issue #497

---

src/main/kotlin/sc/iview/SciView.kt

Improve the cleanup when disposing of a SciView.

Use correct node deletion logic when disposing of sciview

---

src/main/java/sc/iview/commands/edit/DeleteObject.java
src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/view/SetLUT.kt
src/main/kotlin/sc/iview/commands/view/ToggleBoundingGrid.kt

Closes https://github.com/scenerygraphics/sciview/issues/241
When implementing this I found that the only command where there is a clear need is DeleteNode, but SetLUT also makes sense we just don't have examples where a `Volume` is a child of another `Volume`. 
However, I do see the potential for other things that can be applied to Node's recursively, like adjusting position through the inspector.

Add recursive options for node deletion, set LUT, and toggle bounding boxes

---

.github/workflows/build.yml
build.gradle.kts
gradle.properties
src/main/kotlin/sc/iview/SciView.kt

This branch fixes the GitHub Actions workflow declaration to match the current integration branch name, after the rename from master to main.
It also updates the SciJava BOM version to the latest, version 36.0.0, and simplifies some code in the SciJava context creation.

Fix the CI, plus other small updates

---

src/main/kotlin/sc/iview/commands/edit/Properties.kt

Closes https://github.com/scenerygraphics/sciview/issues/509
Voxel size is connected to a `Node`'s `scale` which is already editable.
TY @imagejan for help with non-editable Properties

Display Volume's width, height, depth in Properties panel

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/sciview/publish.gradle.kts
gradle.properties
settings.gradle.kts

This PR fixes some issues related to versions not declared correctly in Maven publications. Furthermore:
* Gradle metadata is not attached anymore to Maven publications
* on the command line or in `gradle.properties`, the `customVersion` property can be defined. If set to `git`, this will lead to jitpack-like behaviour, where the first seven characters of the current git hash are used as version.
* logging behaviour is improved, with `Command`s discovered by the annotation processor being logged, as well as pom-scijava-managed dependencies

Fix Maven release issues

---

src/main/kotlin/sc/iview/SciView.kt

This fixes an issue where adding new objects to the scene would be slowed down by the fact that each new node would always be set as the active node. This would also cause excessive log outputs about each active node like:
```
[INFO] Custom module found: null
[INFO] Adding input scaleX/Scale X
[INFO] Custom module found: null
[INFO] Adding input scaleY/Scale Y
[INFO] Custom module found: null
[INFO] Adding input scaleZ/Scale Z
[INFO] Custom module found: null
[INFO] Adding input rotationPhi/Rotation Phi
[INFO] Custom module found: null
[INFO] Adding input rotationTheta/Rotation Theta
[INFO] Custom module found: null
[INFO] Adding input rotationPsi/Rotation Psi
```
With this fix, new nodes are only considered active when `centerOnNewNodes` is set to `true`.

SciView: set active node only when centerOnNewNodes is true

---

src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/edit/Properties.kt
src/main/kotlin/sc/iview/ui/SwingGroupingInputHarvester.kt
src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt

This PR improves the inspector in the following ways:
* the font size is changed to 90% the regular font size to accommodate more controls in the inspector
* the MigLayout managers for all the inspector's constituents are changed to decrease white space in the inspector and make things more compact
* the transfer function editor for volumes now correctly shows up under the Volume group and transforms correctly
* in `SwingGroupingInputHarvester`, the group names are saved to the name of the respective component, such that they are identifiable later on in the lifecycle

Inspector improvements

---

build.gradle.kts

The version property for bigvolumeviewer was missing from the pom.xml unfortunately.

Add version property for bigvolumeviewer, fix lwjgl version to 3.3.3

---

build.gradle.kts
src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/add/AddCylinder.kt
src/main/kotlin/sc/iview/commands/add/AddOrientationCompass.kt
src/main/kotlin/sc/iview/commands/add/AddPointLight.kt

Partially fixes https://github.com/scenerygraphics/sciview/issues/565

Fixes for add object errors

---

build.gradle.kts
gradle.properties
src/main/kotlin/sc/iview/commands/add/AddOrientationCompass.kt

This PR bumps scenery to 0.11.0, scijava-common to 2.98.0 and Kotlin to 1.9.23. It also adjusts the use of the depth test API in AddOrientationCompass due to an API change in scenery 0.11.0.

Bump scenery to 0.11.0

---

src/main/kotlin/sc/iview/SciView.kt

Unfortunately, calling it from the EDT creates a deadlock.
SciJava Common registers a JVM shutdown hook thread that calls `dispose()` on AWT windows it manages (e.g. the main ImageJ2 window), but `Window#dispose()` internally runs some logic via `EventQueue.invokeAndWait`.
But meanwhile, the `System.exit` call triggers the shutdown hooks, which use `Thread#join` to wait for them to finish, thus blocking the EDT. So the `invokeAndWait` disposing the window can never finish.
Therefore, as a workaround here, we avoid the problem by exiting the JVM from a new thread instead.
Might fix #538.

Avoid calling System.exit from the EDT

---

build.gradle.kts
src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/commands/add/AddVolume.kt
src/main/kotlin/sc/iview/commands/demo/advanced/LoadCremiDatasetAndNeurons.kt
src/main/kotlin/sc/iview/commands/demo/advanced/LoadFlybrainOutOfCore.kt
src/main/kotlin/sc/iview/commands/edit/Properties.kt
src/main/kotlin/sc/iview/ui/SwingMainWindow.kt

This PR fixes the scaling for volume rendering. In addition, it allows sciview's main viewport to become a drop target for files.
Depends on scenerygraphics/scenery#709

Fix volume rendering scaling

---

build.gradle.kts

This PR bumps scenery to 0.11.2 and removes some superfluous dependencies (👀  @kephale 😂).

Bump scenery 0.11.2

---

src/main/kotlin/sc/iview/SciView.kt

This should fix the slow deletion process for large groups of objects. Previously every child node deletion and every recursive call used `activePublish = true`, which slowed down sciview by a lot.

Fix: recursive delete calls no longer use activePublish

---

build.gradle.kts
src/main/kotlin/sc/iview/commands/MenuWeights.kt
src/main/kotlin/sc/iview/commands/demo/advanced/InstancingBenchmark.kt

This PR adds a benchmark to the `Demo > Advanced` menu.
It allows you to compare the conventional means of node publishing with instanced geometry, using spheres as objects.
The benchmark type can be run in four ways:
- publish each node separately
- publish all nodes cumulatively at the end
- populate the scene with instanced geometry sequentially
- populate the scene with instanced geometry using a parallel stream over the array, which is even faster
There are also parameters for the number of (instanced) particles (defaults to `1000`) and the spread in each dimension.

Instancing benchmark demo

---

src/main/java/sc/iview/commands/file/ExportN5.java
src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/ui/ContextPopUp.kt

Scenery removed the `Node.nodeType` property in version 0.11.2. This PR fixes the occurrences of `nodeType` in Sciview and uses java classes instead, which is what @skalarproduktraum suggested.

fix: removed nodeType dependency on scenery

---

src/main/kotlin/sc/iview/SciView.kt

When toggling VR, either via the API or the "view" menu button, the tracking would successfully initialize but the stereo rendering wouldn't switch on. Only after toggling it off and on again would it work.
This fix (credit to @skalarproduktraum) now also enables stereo rendering on toggling VR.

SciView: fix VR toggling to change to stereo rendering

---

src/main/kotlin/sc/iview/commands/demo/animation/VolumeTimeseriesDemo.kt

The initial scale on the Volume Timeseries demo led to the volume being larger than the floor. This makes it more reasonable.

Fix scale to be reasonable

---

src/main/kotlin/sc/iview/SciView.kt
src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt

Previously each node deletion would trigger a scene graph rebuild. This change adds a flag that triggers a scene graph rebuild only once per frame. 
Closes https://github.com/scenerygraphics/sciview/issues/578

Only rebuild scene graph once per Renderer frame
